//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP_3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategorija> Kategorijas { get; set; }
        public virtual DbSet<PerkamaPreke> PerkamaPrekes { get; set; }
        public virtual DbSet<Preke> Prekes { get; set; }
        public virtual DbSet<Transakcijo> Transakcijos { get; set; }
        public virtual DbSet<Vartotoja> Vartotojas { get; set; }
        public virtual DbSet<prekiu_perkamumas> prekiu_perkamumas { get; set; }
        public virtual DbSet<Suma> Sumas { get; set; }
    }
}
