//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP_3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities1 : DbContext
    {
        public dbEntities1()
            : base("name=dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategorija> Kategorija { get; set; }
        public virtual DbSet<PerkamaPreke> PerkamaPreke { get; set; }
        public virtual DbSet<Preke> Preke { get; set; }
        public virtual DbSet<Transakcijos> Transakcijos { get; set; }
        public virtual DbSet<Vartotojas> Vartotojas { get; set; }
        public virtual DbSet<prekiu_perkamumas> prekiu_perkamumas { get; set; }
        public virtual DbSet<Suma> Suma { get; set; }
    }
}
