//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcijos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transakcijos()
        {
            this.PerkamaPreke = new HashSet<PerkamaPreke>();
        }
    
        public int transakcijosID { get; set; }
        public string VartotojoVardas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerkamaPreke> PerkamaPreke { get; set; }
        public virtual Vartotojas Vartotojas { get; set; }
    }
}
