//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vartotojas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vartotojas()
        {
            this.Transakcijos = new HashSet<Transakcijos>();
        }
    
        public string VartotojoVardas { get; set; }
        public string Slaptazodis { get; set; }
        public string Miestas { get; set; }
        public string Gatve { get; set; }
        public string Namas { get; set; }
        public string Butas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcijos> Transakcijos { get; set; }
    }
}
